### ISSUE TITLE
Contribute traditional Multi-class Neural Networks to repository

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#12]
In the repository multiple machine learning techniques are verified. Therefore, application of traditional Multi-class Neural Networks should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: NN](https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html)
2. [MLP Classifier](https://en.wikipedia.org/wiki/Multilayer_perceptron)

Create a well documented .ipynb file detailing your implementation.

**Comment by vedant130701** [comment]
I would like to contribute to this. I have used the MLP classifier previously in a project.

**Comment by onosyoono** [comment]
Cool please go ahead
