### ISSUE TITLE
Contribute Extra Tree Classifiers - Standard and Ensemble

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#13]
In the repository multiple machine learning techniques are verified. Therefore, application of Extra Tree Classifier should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: Extra Tree Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.tree.ExtraTreeClassifier.html#sklearn.tree.ExtraTreeClassifier)
2. [SkLearn: Ensemble Extra Tree Classifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html#sklearn.ensemble.ExtraTreesClassifier)

Create a well documented .ipynb file detailing your implementation.

**Comment by PSY27** [comment]
hey i want to contribute to this as well
can you assign this to me

**Comment by PSY27** [comment]
i will do both

**Comment by onosyoono** [comment]
Ok fine. Please proceed
