### ISSUE TITLE
Contribute Logistic Regression

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#14]
In the repository multiple machine learning techniques are verified. Therefore, application of Logistic Regression should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: LR](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression)
2. [LR](https://en.wikipedia.org/wiki/Logistic_regression)

Create a well documented .ipynb file detailing your implementation.

**Comment by AmanPriyanshu** [comment]
I would like to contribute to this problem statement!

**Comment by onosyoono** [comment]
Sure just make sure its Logistic Regression only and not a complex networks

**Comment by AmanPriyanshu** [comment]
Cool!
