### ISSUE TITLE
Contribute Ensemble-Tree Based Models

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#2]
In the repository multiple machine learning techniques are verified. Therefore, application of ensemble techniques similar to decision trees should be a good contribution. For further details take a look at the following resources:

1. [sklearn.ensemble: Ensemble Methods](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.ensemble)
2. [Decision Trees](https://en.wikipedia.org/wiki/Decision_tree)

Create a well documented .ipynb file detailing your implementation.

**Comment by PSY27** [comment]
I would like to try this out I have previous experience in machine learning

**Comment by onosyoono** [comment]
If you have previous experience with ensemble methods, you can go ahead.

**Comment by PSY27** [comment]
alright 👍
