### ISSUE TITLE
Contribute Naive Bayes

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#4]
In the repository multiple machine learning techniques are verified. Therefore, application of Naive Bayes should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: Naive Bayes](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.BernoulliNB.html#sklearn.naive_bayes.BernoulliNB)
2. [Naive Bayes](https://en.wikipedia.org/wiki/Naive_Bayes_classifier)

Create a well documented .ipynb file detailing your implementation.

**Comment by AmanPriyanshu** [comment]
Can I try Naive Bayes I believe I can implement it quickly!

**Comment by onosyoono** [comment]
Yup sure, however, make sure you stick to Bernoulli variant for multi-class

**Comment by AmanPriyanshu** [comment]
Definitely! if you could please assign me this issue, I will proceed with the implementation.

**Comment by AmanPriyanshu** [comment]
I have completed the task. I am opening a pull request under the name Naive Bayes Contribution

**Comment by onosyoono** [comment]
Cool thanks for the contribution.
