### ISSUE TITLE
Contribute SVM

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#6]
In the repository multiple machine learning techniques are verified. Therefore, application of SVM should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: SVM](https://scikit-learn.org)
2. [SVM](https://en.wikipedia.org/wiki/Support-vector_machine)

Create a well documented .ipynb file detailing your implementation.

**Comment by vedant130701** [comment]
I would like to contribute

**Comment by onosyoono** [comment]
Do you know sklearn implementation? This repository works as an aggregator of classification algorithms.

**Comment by vedant130701** [comment]
Yes I have worked on sklearn classification algorithms before. Please assign me this issue.

**Comment by onosyoono** [comment]
Ok. Looking forward implementation

**Comment by onosyoono** [comment]
Is your Pull Request for SVM this: https://github.com/onosyoono/Programming-Language-Classifier/pull/7 ?

**Comment by vedant130701** [comment]
Yes it is.
