### ISSUE TITLE
Contribute KNN to classifier

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#8]
In the repository multiple machine learning techniques are verified. Therefore, application of KNN should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: KNN](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier)
2. [KNN](https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm)

Create a well documented .ipynb file detailing your implementation.

**Comment by harsh-singh-rathore** [comment]
I can work on knn using sklearn

**Comment by onosyoono** [comment]
Fine, if you require any aid, you can check out tutorial implementations.
