### ISSUE TITLE
Contribute RNC to repository

### ISSUE THREAD

**Issue by onosyoono** [onosyoono/Programming-Language-Classifier#9]
In the repository multiple machine learning techniques are verified. Therefore, application of Radius Neighbors Classifier should be a good contribution. For further details take a look at the following resources:

1. [SKLearn: RNC](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.RadiusNeighborsClassifier.html#sklearn.neighbors.RadiusNeighborsClassifier)
2. [RNC](https://en.wikipedia.org/wiki/Nearest_neighbor_search)

Create a well documented .ipynb file detailing your implementation.

**Comment by AmanPriyanshu** [comment]
Hey, I have previous experience with Radius Neighbours Classifier, and I think I can do this implementation

**Comment by onosyoono** [comment]
Ok, cool since you have successfully completed one already. I'll assign it to you!
